/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SigsInterface extends ethers.utils.Interface {
  functions: {
    "secretHash(uint256)": FunctionFragment;
    "_verifyMessage(address,uint256,address,string,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "secretHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "_verifyMessage",
    values: [string, BigNumberish, string, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "secretHash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_verifyMessage",
    data: BytesLike
  ): Result;

  events: {};
}

export class Sigs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SigsInterface;

  functions: {
    secretHash(
      block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _verifyMessage(
      _slpToken: string,
      _amount: BigNumberish,
      _sender: string,
      _transitId: string,
      _secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  secretHash(block: BigNumberish, overrides?: CallOverrides): Promise<string>;

  _verifyMessage(
    _slpToken: string,
    _amount: BigNumberish,
    _sender: string,
    _transitId: string,
    _secret: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    secretHash(block: BigNumberish, overrides?: CallOverrides): Promise<string>;

    _verifyMessage(
      _slpToken: string,
      _amount: BigNumberish,
      _sender: string,
      _transitId: string,
      _secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    secretHash(
      block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _verifyMessage(
      _slpToken: string,
      _amount: BigNumberish,
      _sender: string,
      _transitId: string,
      _secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    secretHash(
      block: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _verifyMessage(
      _slpToken: string,
      _amount: BigNumberish,
      _sender: string,
      _transitId: string,
      _secret: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
