[package]
name = "crypt"
version = "0.2.1"
description = "Let's encrypt your string statically during compile time"
license = "Apache-2.0"

[lib]
proc-macro = true
path = "src/crypt.rs"
name = "crypt"

[dev-dependencies]
expectest = { version = "0.12.0", features = [] }

[dependencies]
quote = "1.0.8"
proc-macro2 = "1.0.24"
lazy_static = "1.4.0"


